name: Run Program Periodically

on:
    # schedule:
    #   - cron: '*/15 6-18 * * *'  # Runs every 15 minutes between 08:00 and 20:59 (UTC+2)
    #   - cron: '*/20 19-20 * * *' # Runs every 15 minutes between 21:00 and 22:59 (UTC+2)
  
    workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
        echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> $GITHUB_ENV

    - name: Clean previous data
      run: rm -rf ./data_weather

    - name: Run script
      run: python master_.py

    - name: Verify data file
      run: |
        ls -l ./data_weather
        cat ./data_weather/visualcrossing.csv