name: Run Program Periodically
on:
  schedule:
    - cron: '13 06,07,13,17,18 * * *' # real schedule (UTC+2) -> 8:13, 9:13, 15:13, 19:13, 20:13
  workflow_dispatch: # Allows manual triggering
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python sequential_run.py
